name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # Install deps
      - name: Install dependencies
        run: npm ci

      # Run lint
      - name: Run ESLint
        run: npm run lint

      # Run tests
      - name: Run Tests
        run: npm test
